### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by farnaf** [erwinmadjus/Week-2-Lab-Report#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
- [x] All relevant code examples written with backticks (```)
  - please format all terminal commands as code (e.g., cd, $ ssh cs15lwi22zz@ieng6.ucsd.edu, ect)
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
- [x] Lab report is on its own page, not the index page
- [x] Last example counts keystrokes and shows how to run remotely saving time
  - please make sure this part of your lab report completely covers [this part from lab 1](https://ucsd-cse15l-w22.github.io/week/week1/#part-7-making-remote-running-even-more-pleasant)
  - you're missing description of how to optimize remote running, corresponding screenshot, and keystroke count
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
nice job 😃
feel free to comment below any questions related to the rubric/feedback!

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by erwinmadjus** [comment]
Hello,

Quick question, how would I put my Lab Report on its own page?

**Comment by erwinmadjus** [comment]
Wait, I think I got it, I would just have to call the .md file like this?

[Lab Report 1](LabReport1.md)

**Comment by erwinmadjus** [comment]
Wait, I think I got it, I would just have to call the .md file like this?

[Lab Report 1] (LabReport1.md)


where the space between that isn't included.
